// <auto-generated />
using System;
using ECS_Logistics.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ECS_Logistics.Migrations
{
    [DbContext(typeof(MySqlDbContext))]
    partial class MySqlDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("ECS_Logistics.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<DateTime>("DateAdded")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("date_added");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<DateTime>("DateAdded"));

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("date_modified");

                    b.Property<int>("ProductBrandId")
                        .HasColumnType("int")
                        .HasColumnName("product_brand_id");

                    b.Property<int>("ProductCategoryId")
                        .HasColumnType("int")
                        .HasColumnName("product_category_id");

                    b.Property<string>("ProductColor")
                        .HasColumnType("longtext")
                        .HasColumnName("product_color");

                    b.Property<string>("ProductCondition")
                        .HasColumnType("longtext")
                        .HasColumnName("product_condition");

                    b.Property<string>("ProductDescription")
                        .HasColumnType("longtext")
                        .HasColumnName("product_description");

                    b.Property<string>("ProductDimensions")
                        .HasColumnType("longtext")
                        .HasColumnName("product_dimensions");

                    b.Property<string>("ProductImage")
                        .HasColumnType("longtext")
                        .HasColumnName("product_image");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("product_name");

                    b.Property<float>("ProductPrice")
                        .HasColumnType("float")
                        .HasColumnName("product_price");

                    b.Property<int>("ProductQuantity")
                        .HasColumnType("int")
                        .HasColumnName("product_quantity");

                    b.Property<float>("ProductWeight")
                        .HasColumnType("float")
                        .HasColumnName("product_weight");

                    b.Property<int>("SubCategoryId")
                        .HasColumnType("int")
                        .HasColumnName("sub_category_id");

                    b.HasKey("ProductId");

                    b.ToTable("product", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
